# Dataset Paths
root: ./mlb-youtube/clips/
label: ./mlb-youtube/label_frames.txt

# Classification
num_classes: 2

# Model Configs
weights: 
new_length: 3
num_segments: 8
frame_interval: 2
no_partialbn: True

# Training Configs
epochs: 60         
batch_size: 8      
warmup_epoch: 0
clip_gradient: 20

# Optimizer & Scheduler
lr: 0.002
momentum: 0.9
weight_decay: 0.0001
lr_scheduler: step
lr_decay_rate: 0.1
lr_steps: [10, 20]

# Runtime Configs
num_workers: 6
print_freq: 20
eval_freq: 1
